# Problem Statement

## **Business Context**

"Visit with Us," a leading travel company, is revolutionizing the tourism industry by leveraging data-driven strategies to optimize operations and customer engagement. While introducing a new package offering, such as the Wellness Tourism Package, the company faces challenges in targeting the right customers efficiently. The manual approach to identifying potential customers is inconsistent, time-consuming, and prone to errors, leading to missed opportunities and suboptimal campaign performance.

To address these issues, the company aims to implement a scalable and automated system that integrates customer data, predicts potential buyers, and enhances decision-making for marketing strategies. By utilizing an MLOps pipeline, the company seeks to achieve seamless integration of data preprocessing, model development, deployment, and CI/CD practices for continuous improvement. This system will ensure efficient targeting of customers, timely updates to the predictive model, and adaptation to evolving customer behaviors, ultimately driving growth and customer satisfaction.

## **Objective**

As an MLOps Engineer at "Visit with Us," your responsibility is to design and deploy an MLOps pipeline on GitHub to automate the end-to-end workflow for predicting customer purchases. The primary objective is to build a model that predicts whether a customer will purchase the newly introduced Wellness Tourism Package before contacting them. The pipeline will include data cleaning, preprocessing, transformation, model building, training, evaluation, and deployment, ensuring consistent performance and scalability. By leveraging GitHub Actions for CI/CD integration, the system will enable automated updates, streamline model deployment, and improve operational efficiency. This robust predictive solution will empower policymakers to make data-driven decisions, enhance marketing strategies, and effectively target potential customers, thereby driving customer acquisition and business growth.

## **Data Description**

The dataset contains customer and interaction data that serve as key attributes for predicting the likelihood of purchasing the Wellness Tourism Package. The detailed attributes are:

**Customer Details**
- **CustomerID:** Unique identifier for each customer.
- **ProdTaken:** Target variable indicating whether the customer has purchased a package (0: No, 1: Yes).
- **Age:** Age of the customer.
- **TypeofContact:** The method by which the customer was contacted (Company Invited or Self Inquiry).
- **CityTier:** The city category based on development, population, and living standards (Tier 1 > Tier 2 > Tier 3).
- **Occupation:** Customer's occupation (e.g., Salaried, Freelancer).
- **Gender:** Gender of the customer (Male, Female).
- **NumberOfPersonVisiting:** Total number of people accompanying the customer on the trip.
- **PreferredPropertyStar:** Preferred hotel rating by the customer.
- **MaritalStatus:** Marital status of the customer (Single, Married, Divorced).
- **NumberOfTrips:** Average number of trips the customer takes annually.
- **Passport:** Whether the customer holds a valid passport (0: No, 1: Yes).
- **OwnCar:** Whether the customer owns a car (0: No, 1: Yes).
- **NumberOfChildrenVisiting:** Number of children below age 5 accompanying the customer.
- **Designation:** Customer's designation in their current organization.
- **MonthlyIncome:** Gross monthly income of the customer.

**Customer Interaction Data**
- **PitchSatisfactionScore:** Score indicating the customer's satisfaction with the sales pitch.
- **ProductPitched:** The type of product pitched to the customer.
- **NumberOfFollowups:** Total number of follow-ups by the salesperson after the sales pitch.-
- **DurationOfPitch:** Duration of the sales pitch delivered to the customer.

# Model Building

In [1]:
import os

os.makedirs("tourism_project", exist_ok=True)
os.makedirs("tourism_project/data", exist_ok=True)
os.makedirs("tourism_project/model_building", exist_ok=True)
os.makedirs("tourism_project/deployment", exist_ok=True)

## Data Registration

In [4]:
os.makedirs("tourism_project/data", exist_ok=True)

Once the **data** folder created after executing the above cell, please upload the **tourism.csv** in to the folder

## Data Preparation

In [5]:
import pandas as pd

# Load the dataset
df = pd.read_csv("tourism_project/data/tvk.csv")

# Display dataset shape
print("Dataset Shape:", df.shape)

# Display first 5 rows
df.head()

Dataset Shape: (4128, 21)

,Unnamed: 0,CustomerID,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,...,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,Designation,MonthlyIncome
0,0,200000,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3,...,Deluxe,3.0,Single,1.0,1,2,1,0.0,Manager,20993.0
1,1,200001,0,49.0,Company Invited,1,14.0,Salaried,Male,3,...,Deluxe,4.0,Divorced,2.0,0,3,1,2.0,Manager,20130.0
2,2,200002,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,3,...,Basic,3.0,Single,7.0,1,3,0,0.0,Executive,17090.0
3,3,200003,0,33.0,Company Invited,1,9.0,Salaried,Female,2,...,Basic,3.0,Divorced,2.0,1,5,1,1.0,Executive,17909.0
4,5,200005,0,32.0,Company Invited,1,8.0,Salaried,Male,3,...,Basic,3.0,Single,1.0,0,5,1,1.0,Executive,18068.0

In [6]:
# Check dataset information
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4128 entries, 0 to 4127
Data columns (total 21 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Unnamed: 0                4128 non-null   int64
 1   CustomerID                4128 non-null   int64
 2   ProdTaken                 4128 non-null   int64
 3   Age                       4128 non-null   float64
 4   TypeofContact             4128 non-null   object
 5   CityTier                  4128 non-null   int64
 6   DurationOfPitch           4128 non-null   float64
 7   Occupation                4128 non-null   object
 8   Gender                    4128 non-null   object
 9   NumberOfPersonVisiting    4128 non-null   int64
 10  NumberOfFollowups         4128 non-null   float64
 11  ProductPitched            4128 non-null   object
 12  PreferredPropertyStar     4128 non-null   float64
 13  MaritalStatus             4128 non-null   object
 14  NumberOfTrips             4128 non-null   float64
 15  Passport                  4128 non-null   int64
 16  PitchSatisfactionScore    4128 non-null   int64
 17  OwnCar                    4128 non-null   int64
 18  NumberOfChildrenVisiting  4128 non-null   float64
 19  Designation               4128 non-null   object
 20  MonthlyIncome             4128 non-null   float64
dtypes: float64(7), int64(8), object(6)
memory usage: 677.4+ KB

In [7]:
# Check missing values
df.isnull().sum()

Unnamed: 0                  0
CustomerID                  0
ProdTaken                   0
Age                         0
TypeofContact               0
CityTier                    0
DurationOfPitch             0
Occupation                  0
Gender                      0
NumberOfPersonVisiting      0
NumberOfFollowups           0
ProductPitched              0
PreferredPropertyStar       0
MaritalStatus               0
NumberOfTrips               0
Passport                    0
PitchSatisfactionScore      0
OwnCar                      0
NumberOfChildrenVisiting    0
Designation                 0
MonthlyIncome               0
dtype: int64

In [8]:
df.describe(include="all")

,Unnamed: 0,CustomerID,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,...,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,Designation,MonthlyIncome
count,4128.000000,4128.000000,4128.000000,4128.000000,4128,4128.000000,4128.000000,4128,4128,4128.000000,...,4128,4128.000000,4128,4128.0000,4128.000000,4128.000000,4128.000000,4128.000000,4128,4128.000000
unique,NaN,NaN,NaN,NaN,2,NaN,NaN,4,3,NaN,...,5,NaN,4,NaN,NaN,NaN,NaN,NaN,5,NaN
top,NaN,NaN,NaN,NaN,Self Enquiry,NaN,NaN,Salaried,Male,NaN,...,Basic,NaN,Married,NaN,NaN,NaN,NaN,NaN,Executive,NaN
freq,NaN,NaN,NaN,NaN,2918,NaN,NaN,1999,2463,NaN,...,1615,NaN,1990,NaN,NaN,NaN,NaN,NaN,1615,NaN
mean,2527.763808,202527.763808,0.193072,37.231831,NaN,1.663275,15.584787,NaN,NaN,2.949370,...,NaN,3.578488,NaN,3.2953,0.295300,3.060804,0.612161,1.223595,NaN,23178.464147
std,1409.439133,1409.439133,0.394757,9.174521,NaN,0.920640,8.398142,NaN,NaN,0.718818,...,NaN,0.795031,NaN,1.8563,0.456233,1.363064,0.487317,0.852685,NaN,4506.614622
min,0.000000,200000.000000,0.000000,18.000000,NaN,1.000000,5.000000,NaN,NaN,1.000000,...,NaN,3.000000,NaN,1.0000,0.000000,1.000000,0.000000,0.000000,NaN,1000.000000
25%,1320.750000,201320.750000,0.000000,31.000000,NaN,1.000000,9.000000,NaN,NaN,2.000000,...,NaN,3.000000,NaN,2.0000,0.000000,2.000000,0.000000,1.000000,NaN,20751.000000
50%,2603.500000,202603.500000,0.000000,36.000000,NaN,1.000000,14.000000,NaN,NaN,3.000000,...,NaN,3.000000,NaN,3.0000,0.000000,3.000000,1.000000,1.000000,NaN,22418.000000
75%,3748.250000,203748.250000,0.000000,43.000000,NaN,3.000000,20.000000,NaN,NaN,3.000000,...,NaN,4.000000,NaN,4.0000,1.000000,4.000000,1.000000,2.000000,NaN,25301.000000
max,4887.000000,204887.000000,1.000000,61.000000,NaN,3.000000,127.000000,NaN,NaN,5.000000,...,NaN,5.000000,NaN,22.0000,1.000000,5.000000,1.000000,3.000000,NaN,98678.000000

In [9]:
# -------------------------------
# Data Cleaning
# -------------------------------

# Remove unnecessary columns
df = df.drop(columns=["Unnamed: 0", "CustomerID"])

print("Columns after dropping unnecessary fields:")
print(df.columns)

print("\nNew Shape:", df.shape)

df.head()

Columns after dropping unnecessary fields:
Index(['ProdTaken', 'Age', 'TypeofContact', 'CityTier', 'DurationOfPitch',
       'Occupation', 'Gender', 'NumberOfPersonVisiting', 'NumberOfFollowups',
       'ProductPitched', 'PreferredPropertyStar', 'MaritalStatus',
       'NumberOfTrips', 'Passport', 'PitchSatisfactionScore', 'OwnCar',
       'NumberOfChildrenVisiting', 'Designation', 'MonthlyIncome'],
      dtype='object')

New Shape: (4128, 19)

,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,Designation,MonthlyIncome
0,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3,3.0,Deluxe,3.0,Single,1.0,1,2,1,0.0,Manager,20993.0
1,0,49.0,Company Invited,1,14.0,Salaried,Male,3,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,2.0,Manager,20130.0
2,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,3,4.0,Basic,3.0,Single,7.0,1,3,0,0.0,Executive,17090.0
3,0,33.0,Company Invited,1,9.0,Salaried,Female,2,3.0,Basic,3.0,Divorced,2.0,1,5,1,1.0,Executive,17909.0
4,0,32.0,Company Invited,1,8.0,Salaried,Male,3,3.0,Basic,3.0,Single,1.0,0,5,1,1.0,Executive,18068.0

### Observation

The columns **Unnamed: 0** and **CustomerID** were removed because they do not contribute to predicting whether a customer purchases the Wellness Tourism Package. The remaining 19 features will be used for model training.

In [10]:
from sklearn.preprocessing import LabelEncoder

# Create a LabelEncoder object
encoder = LabelEncoder()

# Identify categorical columns
categorical_columns = df.select_dtypes(include='object').columns

print("Categorical Columns:")
print(categorical_columns)

# Encode categorical columns
for col in categorical_columns:
    df[col] = encoder.fit_transform(df[col])

print("\nEncoding completed successfully!")

df.head()

Categorical Columns:
Index(['TypeofContact', 'Occupation', 'Gender', 'ProductPitched',
       'MaritalStatus', 'Designation'],
      dtype='object')

Encoding completed successfully!

,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,Designation,MonthlyIncome
0,1,41.0,1,3,6.0,2,1,3,3.0,1,3.0,2,1.0,1,2,1,0.0,2,20993.0
1,0,49.0,0,1,14.0,2,2,3,4.0,1,4.0,0,2.0,0,3,1,2.0,2,20130.0
2,1,37.0,1,1,8.0,0,2,3,4.0,0,3.0,2,7.0,1,3,0,0.0,1,17090.0
3,0,33.0,0,1,9.0,2,1,2,3.0,0,3.0,0,2.0,1,5,1,1.0,1,17909.0
4,0,32.0,0,1,8.0,2,2,3,3.0,0,3.0,2,1.0,0,5,1,1.0,1,18068.0

### Observation

All categorical columns were converted into numerical values using Label Encoding because machine learning algorithms require numerical inputs.

In [11]:
from sklearn.model_selection import train_test_split

# Features and Target
X = df.drop("ProdTaken", axis=1)
y = df["ProdTaken"]

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("Training Features Shape :", X_train.shape)
print("Testing Features Shape  :", X_test.shape)
print("Training Labels Shape   :", y_train.shape)
print("Testing Labels Shape    :", y_test.shape)

Training Features Shape : (3302, 18)
Testing Features Shape  : (826, 18)
Training Labels Shape   : (3302,)
Testing Labels Shape    : (826,)

### Observation

The dataset was divided into training (80%) and testing (20%) sets using stratified sampling to preserve the class distribution. The training dataset will be used for model training, while the testing dataset will be used for model evaluation.

In [12]:
# Create train dataset
train_df = X_train.copy()
train_df["ProdTaken"] = y_train

# Create test dataset
test_df = X_test.copy()
test_df["ProdTaken"] = y_test

# Save the datasets
train_df.to_csv("tourism_project/data/train.csv", index=False)
test_df.to_csv("tourism_project/data/test.csv", index=False)

print("Train and Test datasets saved successfully.")

Train and Test datasets saved successfully.

In [13]:
import os

print(os.listdir("tourism_project/data"))

['test.csv', 'train.csv', 'tvk.csv']

### Observation

The processed dataset was split into training and testing datasets and stored locally inside the project's data folder for further model training and evaluation.

# Model Training and Registration with Experimentation Tracking

In this section, the processed dataset is loaded and a machine learning model is trained to predict whether a customer will purchase the Wellness Tourism Package. Hyperparameter tuning is performed using GridSearchCV to identify the best-performing model. The trained model is then evaluated using multiple performance metrics and saved for deployment.

In [15]:
import pandas as pd

# Load the processed training and testing datasets
train_df = pd.read_csv("tourism_project/data/train.csv")
test_df = pd.read_csv("tourism_project/data/test.csv")

print("Training Dataset Shape:", train_df.shape)
print("Testing Dataset Shape :", test_df.shape)

train_df.head()

Training Dataset Shape: (3302, 19)
Testing Dataset Shape : (826, 19)

,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,Designation,MonthlyIncome,ProdTaken
0,55.0,1,1,17.0,3,1,4,4.0,1,5.0,3,8.0,1,1,0,1.0,2,23118.0,0
1,39.0,1,1,9.0,2,2,3,4.0,0,3.0,3,7.0,1,4,0,2.0,1,22622.0,0
2,42.0,0,2,8.0,3,2,3,1.0,1,5.0,0,1.0,0,2,0,2.0,2,21272.0,0
3,37.0,1,1,12.0,2,1,3,5.0,0,5.0,0,2.0,1,2,1,1.0,1,98678.0,0
4,23.0,1,1,7.0,2,2,3,5.0,1,3.0,0,8.0,0,2,1,1.0,2,23453.0,0

### Observation

The processed training and testing datasets were successfully loaded. These datasets will now be used for model training and performance evaluation.

In [16]:
# Split into Features and Target

X_train = train_df.drop("ProdTaken", axis=1)
y_train = train_df["ProdTaken"]

X_test = test_df.drop("ProdTaken", axis=1)
y_test = test_df["ProdTaken"]

print(X_train.shape)
print(X_test.shape)

(3302, 18)
(826, 18)

In [18]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(random_state=42)

In [26]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier
import pandas as pd

# Define the model
rf_model = RandomForestClassifier(random_state=42)

# Hyperparameter Grid
param_grid = {
    "n_estimators": [100, 200],
    "max_depth": [5, 10, 15, None],
    "min_samples_split": [2, 5],
    "min_samples_leaf": [1, 2]
}

# Grid Search
grid_search = GridSearchCV(
    estimator=rf_model,
    param_grid=param_grid,
    cv=5,
    scoring="accuracy",
    n_jobs=-1,
    verbose=2
)

# Train
grid_search.fit(X_train, y_train)

print("\nBest Parameters")
print(grid_search.best_params_)

print("\nBest Cross Validation Accuracy")
print(round(grid_search.best_score_,4))

Fitting 5 folds for each of 32 candidates, totalling 160 fits

Best Parameters
{'max_depth': 15, 'min_samples_leaf': 1, 'min_samples_split': 2, 'n_estimators': 100}

Best Cross Validation Accuracy
0.9164

In [27]:
experiment_log = pd.DataFrame({
    "Parameter": grid_search.best_params_.keys(),
    "Best Value": grid_search.best_params_.values()
})

print("Experiment Tracking")
display(experiment_log)

print("Best CV Accuracy:", round(grid_search.best_score_,4))

Experiment Tracking

           Parameter  Best Value
0          max_depth          15
1   min_samples_leaf           1
2  min_samples_split           2
3       n_estimators         100

Best CV Accuracy: 0.9164

In [28]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score
)

best_model = grid_search.best_estimator_

y_pred = best_model.predict(X_test)

metrics = pd.DataFrame({
    "Metric":[
        "Accuracy",
        "Precision",
        "Recall",
        "F1 Score"
    ],
    "Value":[
        accuracy_score(y_test,y_pred),
        precision_score(y_test,y_pred),
        recall_score(y_test,y_pred),
        f1_score(y_test,y_pred)
    ]
})

display(metrics)

      Metric     Value
0   Accuracy  0.916465
1  Precision  0.924528
2     Recall  0.616352
3   F1 Score  0.739623

In [29]:
from sklearn.metrics import confusion_matrix, classification_report

print(confusion_matrix(y_test,y_pred))

print(classification_report(y_test,y_pred))

[[659   8]
 [ 61  98]]
              precision    recall  f1-score   support

           0       0.92      0.99      0.95       667
           1       0.92      0.62      0.74       159

    accuracy                           0.92       826
   macro avg       0.92      0.80      0.84       826
weighted avg       0.92      0.92      0.91       826

In [30]:
import joblib

joblib.dump(
    best_model,
    "tourism_project/model_building/wellness_tourism_model.joblib"
)

print("Model saved successfully.")

Model saved successfully.

### Observation

Random Forest was selected as the final model after performing hyperparameter tuning using GridSearchCV. The best-performing model achieved the highest cross-validation accuracy and was saved for deployment. The evaluation metrics indicate the model's ability to predict customer purchases effectively.

In [31]:
import os

print("Files in model_building folder:")
print(os.listdir("tourism_project/model_building"))

Files in model_building folder:
['wellness_tourism_model.joblib']

# Deployment

## Dockerfile

In [32]:
os.makedirs("tourism_project/deployment", exist_ok=True)

In [33]:
%%writefile tourism_project/deployment/Dockerfile
# Use a minimal base image with Python 3.9 installed
FROM python:3.9

# Set the working directory inside the container to /app
WORKDIR /app

# Copy all files from the current directory on the host to the container's /app directory
COPY . .

# Install Python dependencies listed in requirements.txt
RUN pip3 install -r requirements.txt

RUN useradd -m -u 1000 user
USER user
ENV HOME=/home/user \
	PATH=/home/user/.local/bin:$PATH

WORKDIR $HOME/app

COPY --chown=user . $HOME/app

# Define the command to run the Streamlit app on port "8501" and make it accessible externally
CMD ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0", "--server.enableXsrfProtection=false"]

Writing tourism_project/deployment/Dockerfile

## Streamlit App

Please ensure that the web app script is named `app.py`.

In [34]:
%%writefile tourism_project/deployment/app.py

import streamlit as st
import pandas as pd
import joblib

# Load trained model
model = joblib.load("tourism_project/model_building/wellness_tourism_model.joblib")

st.title("Wellness Tourism Package Prediction")

st.write("Enter the customer details below to predict whether the customer is likely to purchase the Wellness Tourism Package.")

# -------------------------------
# User Inputs
# -------------------------------

Age = st.number_input("Age", min_value=18, max_value=100, value=35)

TypeofContact = st.selectbox("Type of Contact", [0,1])

CityTier = st.selectbox("City Tier", [1,2,3])

DurationOfPitch = st.number_input("Duration Of Pitch", value=15.0)

Occupation = st.selectbox("Occupation", [0,1,2,3])

Gender = st.selectbox("Gender", [0,1,2])

NumberOfPersonVisiting = st.number_input("Number Of Person Visiting", value=2)

NumberOfFollowups = st.number_input("Number Of Followups", value=3)

ProductPitched = st.selectbox("Product Pitched",[0,1,2,3,4])

PreferredPropertyStar = st.number_input("Preferred Property Star",value=3)

MaritalStatus = st.selectbox("Marital Status",[0,1,2])

NumberOfTrips = st.number_input("Number Of Trips",value=3)

Passport = st.selectbox("Passport",[0,1])

PitchSatisfactionScore = st.slider("Pitch Satisfaction Score",1,5)

OwnCar = st.selectbox("Own Car",[0,1])

NumberOfChildrenVisiting = st.number_input("Number Of Children Visiting",value=0)

Designation = st.selectbox("Designation",[0,1,2,3,4])

MonthlyIncome = st.number_input("Monthly Income",value=30000.0)

# -------------------------------
# Prediction
# -------------------------------

if st.button("Predict"):

    input_df = pd.DataFrame([[
        Age,
        TypeofContact,
        CityTier,
        DurationOfPitch,
        Occupation,
        Gender,
        NumberOfPersonVisiting,
        NumberOfFollowups,
        ProductPitched,
        PreferredPropertyStar,
        MaritalStatus,
        NumberOfTrips,
        Passport,
        PitchSatisfactionScore,
        OwnCar,
        NumberOfChildrenVisiting,
        Designation,
        MonthlyIncome
    ]], columns=[
        'Age',
        'TypeofContact',
        'CityTier',
        'DurationOfPitch',
        'Occupation',
        'Gender',
        'NumberOfPersonVisiting',
        'NumberOfFollowups',
        'ProductPitched',
        'PreferredPropertyStar',
        'MaritalStatus',
        'NumberOfTrips',
        'Passport',
        'PitchSatisfactionScore',
        'OwnCar',
        'NumberOfChildrenVisiting',
        'Designation',
        'MonthlyIncome'
    ])

    prediction = model.predict(input_df)

    if prediction[0] == 1:
        st.success("The customer is likely to purchase the Wellness Tourism Package.")
    else:
        st.error("The customer is unlikely to purchase the Wellness Tourism Package.")

Writing tourism_project/deployment/app.py

## Dependency Handling

Please ensure that the dependency handling file is named `requirements.txt`.

In [36]:
%%writefile tourism_project/deployment/requirements.txt

streamlit
pandas
numpy
scikit-learn
joblib
huggingface_hub
datasets

Overwriting tourism_project/deployment/requirements.txt

# Hosting

In [37]:
%%writefile tourism_project/deployment/hosting.py

import os

print("Deployment files are ready.")

print("\nFiles available for deployment:")

for file in os.listdir("tourism_project/deployment"):
    print(file)

print("\nUpload these files to your Hugging Face Space:")
print("- app.py")
print("- requirements.txt")
print("- Dockerfile")

Writing tourism_project/deployment/hosting.py

In [38]:
import os

print(os.listdir("tourism_project/deployment"))

['app.py', 'Dockerfile', 'hosting.py', 'requirements.txt']

### Observation

The deployment files were successfully created. A Streamlit application was developed to collect user inputs and predict customer purchase behaviour using the trained Random Forest model. A requirements file was prepared to manage dependencies, and a hosting script was created to facilitate deployment to Hugging Face Spaces.

# Hugging Face Integration

In [39]:
!pip install huggingface_hub datasets -q

  WARNING: The script datasets-cli.exe is installed in 'C:\Users\CMC\AppData\Roaming\Python\Python313\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

In [40]:
import huggingface_hub
import datasets

print("Hugging Face Hub Version:", huggingface_hub.__version__)
print("Datasets Version:", datasets.__version__)

Hugging Face Hub Version: 1.10.1
Datasets Version: 5.0.0

#### Hugging Face Integration

### Dataset Repository

https://huggingface.co/datasets/saiadityalingam3/wellness-tourism-dataset

### Model Repository

https://huggingface.co/saiadityalingam3/wellness-tourism-model

### Observation

The processed datasets (train.csv, test.csv and tvk.csv) were successfully registered in the Hugging Face Dataset Hub. The trained Random Forest model was also uploaded to the Hugging Face Model Hub for model versioning and deployment.

# MLOps Pipeline with Github Actions Workflow

**Note:**

1. Before running the file below, make sure to add the HF_TOKEN to your GitHub secrets to enable authentication between GitHub and Hugging Face.
2. The below code is for a sample YAML file that can be updated as required to meet the requirements of this project.

```
name: Tourism Project Pipeline

on:
  push:
    branches:
      - main  # Automatically triggers on push to the main branch

jobs:

  register-dataset:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: <add_code_here>
      - name: Upload Dataset to Hugging Face Hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: <add_code_here>

  data-prep:
    needs: register-dataset
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: <add_code_here>
      - name: Run Data Preparation
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: <add_code_here>


  model-traning:
    needs: data-prep
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: <add_code_here>
      - name: Start MLflow Server
        run: |
          nohup mlflow ui --host 0.0.0.0 --port 5000 &  # Run MLflow UI in the background
          sleep 5  # Wait for a moment to let the server starts
      - name: Model Building
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: <add_code_here>


  deploy-hosting:
    runs-on: ubuntu-latest
    needs: [model-traning,data-prep,register-dataset]
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: <add_code_here>
      - name: Push files to Frontend Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: <add_code_here>

```

**Note:** To use this YAML file for our use case, we need to

1. Go to the GitHub repository for the project
2. Create a folder named ***.github/workflows/***
3. In the above folder, create a file named ***pipeline.yml***
4. Copy and paste the above content for the YAML file into the ***pipeline.yml*** file

## Requirements file for the Github Actions Workflow

## Github Authentication and Push Files

* Before moving forward, we need to generate a secret token to push files directly from Colab to the GitHub repository.
* Please follow the below instructions to create the GitHub token:
    - Open your GitHub profile.
    - Click on ***Settings***.
    - Go to ***Developer Settings***.
    - Expand the ***Personal access tokens*** section and select ***Tokens (classic)***.
    - Click ***Generate new token***, then choose ***Generate new token (classic)***.
    - Add a note and select all required scopes.
    - Click ***Generate token***.
    - Copy the generated token and store it safely in a notepad.

In [ ]:
# Install Git
!apt-get install git

# Set your Git identity (replace with your details)
!git config --global user.email "<-------GitHub Email Address------->"
!git config --global user.name "<--------GitHub UserName--------->"

# Clone your GitHub repository
!git clone https://github.com/<--------GitHub UserName--------->/<--------GitHub Reponame--------->.git

# Move your folder to the repository directory
!mv /content/tourism_project/ /content/<--------GitHub Reponame--------->

In [ ]:
# Change directory to the cloned repository
%cd <--------GitHub Reponame--------->/

# Add the new folder to Git
!git add .

# Commit the changes
!git commit -m "first commit"

# Push to GitHub (you'll need your GitHub credentials; use a personal access token if 2FA enabled)
!git push https://<--------GitHub UserName--------->:<--------GitHub Token--------->@github.com/<--------GitHub UserName--------->/<--------GitHub Reponame--------->.git

# Output Evaluation

- GitHub (link to repository, screenshot of folder structure and executed workflow)

- Streamlit on Hugging Face (link to HF space, screenshot of Streamlit app)

<font size=6 color="navyblue">Power Ahead!</font>
___